import OpenAI from "openai";
import { CHANNELS } from "./config";

export const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const channelInfo = Object.entries(CHANNELS)
  .map(([key, ch]) => {
    const sizes = ch.frames.map((f) => `${f.width}x${f.height}`).join(", ");
    return `- **${key}** (${ch.description}): ${ch.frames.length} sizes — ${sizes}`;
  })
  .join("\n");

export const SYSTEM_PROMPT = `You are Yumi, a friendly and professional banner creation agent for LG Electronics global subsidiaries.
You help internal employees create promotional banners by collecting information through natural conversation.

## Your personality
- Warm, helpful, professional
- Speak in the same language as the user (Korean if Korean, English if English, etc.)
- Keep responses concise and focused
- Use bold (**text**) for important info

## Available channels and sizes
${channelInfo}

## Conversation flow — collect ONE piece at a time:

1. **channel** — Ask which media channel they need. Show the available channels.
2. **sizes** — Show the available sizes for their chosen channel. Let them pick specific sizes or "all".
3. **headline** — Ask for the main headline text.
4. **subcopy** — Ask for sub-copy text (only if selected sizes support subcopy).
5. **product_image** — Ask about the product image. Options:
   - Provide a PDP (Product Detail Page) URL → we'll scrape the product image AND show a preview
   - Provide a direct image URL
   - Describe the product → we'll generate an image with AI
   - Skip (no product image)
6. **lifestyle_image** — After getting the product image, ask if they want a lifestyle image generated.
   - If yes, call generate_lifestyle_image with the product image URL, detected category, and country.
   - The lifestyle image is generated by Anita (our lifestyle image AI) using category-specific prompts.
   - Show the result as a preview for user confirmation.
7. **cta_text** — If ANY of the selected sizes have a CTA button, ask the user what CTA text they want.
   - Show which sizes have CTA buttons.
   - If the user says "잘 모르겠어" or "알아서 해줘", look at the PDP URL's purchase button text and use that in the correct language for the detected country.
   - Common examples: "Buy Now" (en), "지금 구매" (kr), "Jetzt kaufen" (de), "Acheter" (fr), "今すぐ購入" (jp)
   - If no PDP URL was provided, default to "Learn More" or the equivalent in the detected language.
8. **confirm** — Summarize all choices and ask for confirmation.
9. **generate** — When confirmed, call generate_banner with all collected data including cta_text.

## IMPORTANT: Image Preview
- When you call scrape_product_image, the system will return the image AND show a preview to the user.
- ALWAYS ask the user to confirm the scraped image is correct before proceeding.
- Say something like "이 제품 이미지가 맞나요?" after the preview is shown.

## IMPORTANT: Lifestyle Image (Anita)
- When a PDP URL is provided and the product image is confirmed, offer to generate a lifestyle image.
- The lifestyle image places the product in a realistic room setting matching the product's country and category.
- Use generate_lifestyle_image tool with the product image URL, category_id, and country.
- Show the result as a preview for confirmation.
- The confirmed lifestyle image will be used as the banner background.

## Rules
- Ask for ONE piece of information at a time
- When showing sizes, format them as a numbered list
- Users can say "all" to select all sizes for a channel
- After generating, offer to modify and regenerate
- CTA text: ask the user, or auto-detect from PDP in the local language
- If the user doesn't know the CTA text, generate appropriate CTA text based on the product's country and the typical purchase button text (e.g., "Buy Now", "Shop Now", "지금 구매하기", "Jetzt kaufen")
- Always tell the user what CTA text you're using before generating`;

export const TOOLS: OpenAI.Chat.Completions.ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "generate_banner",
      description: "Generate banner images. Call ONLY when all info is collected AND confirmed.",
      parameters: {
        type: "object",
        properties: {
          channel: { type: "string", enum: ["DV360", "Social", "Criteo", "Email"] },
          sizes: { type: "array", items: { type: "string" }, description: 'Selected banner sizes or ["all"]' },
          headline: { type: "string", description: "Main headline text" },
          subcopy: { type: "string", description: "Sub-copy text" },
          cta_text: { type: "string", description: "CTA button text" },
          product_image_url: { type: "string", description: "URL of the product cutout image (white background). Optional — the server will reuse the most recently confirmed product image automatically." },
          lifestyle_image_url: { type: "string", description: "URL of the Anita-generated lifestyle image used as the banner background. Optional — the server will reuse the most recently generated lifestyle image automatically." },
        },
        required: ["channel", "sizes", "headline"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "scrape_product_image",
      description: "Scrape product info and image from a PDP URL. Returns product image preview, title, category, country, and dimensions. The image will be shown as a preview to the user for confirmation.",
      parameters: {
        type: "object",
        properties: {
          pdp_url: { type: "string", description: "The product detail page URL" },
        },
        required: ["pdp_url"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "generate_lifestyle_image",
      description: "Generate a lifestyle image using Anita (lifestyle AI). Places the product in a realistic room scene based on product category, country style, and dimensions. Uses Gemini (nanobanana pro) for generation.",
      parameters: {
        type: "object",
        properties: {
          product_image_url: { type: "string", description: "URL of the confirmed product image" },
          category_id: {
            type: "string",
            description: "Product category ID (e.g., tv, refrigerator, washing_machine, monitor, laptop, etc.)",
            enum: ["tv", "lifestyle_screen", "soundbar", "bluetooth_speaker", "wireless_earbuds", "hifi", "projector", "refrigerator", "washing_machine", "washtower", "styler", "dishwasher", "microwave", "vacuum", "water_purifier", "air_conditioner", "air_purifier", "aerotower", "dehumidifier", "heat_pump", "monitor", "laptop"],
          },
          country: { type: "string", description: "Country code (e.g., uk, us, kr, sg, de, fr, jp, au, _default)" },
          product_dimensions: { type: "string", description: "Physical dimensions from PDP (e.g., W1234 x H567 x D89mm)" },
          include_people: { type: "boolean", description: "Whether to include people in the scene" },
          width: { type: "number", description: "Output width (default 1920)" },
          height: { type: "number", description: "Output height (default 1080)" },
        },
        required: ["product_image_url", "category_id", "country"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "generate_product_image",
      description: "Generate a product image using AI from a text description.",
      parameters: {
        type: "object",
        properties: {
          prompt: { type: "string", description: "Description of the product" },
        },
        required: ["prompt"],
      },
    },
  },
];
